/*
 * Automatically generated C config: don't edit
 * LTIB version: 9.1.1
 */
#define AUTOCONF_INCLUDED
#define CONFIG_CONFIG_TITLE "LTIB: Freescale MPC8315E RDB PowerPC board"
#define CONFIG_CPU "MPC8315E"
#define CONFIG_PLATFORM_COMMENT "Freescale MPC8315E RDB PowerPC board"
#define CONFIG_VENDOR "Freescale"
#define CONFIG_PLATFORM "mpc8315erdb"
#define CONFIG_GNUTARCH "powerpc"
#define CONFIG_LINTARCH "powerpc"
#define CONFIG_CFGHOST "powerpc-linux"

/*
 * LTIB settings
 */

/*
 * System features
 */
#define CONFIG_FEAT_CACHE_RPMS 1
#define CONFIG_ENDIAN "big"

/*
 * Choose the target C library type
 */
#define CONFIG_GLIBC 1
#undef CONFIG_UCLIBC
#define CONFIG_CHOICE_BASE_LIBS 1
#undef CONFIG_CHOICE_GLIBC
#undef CONFIG_CHOICE_UCLIBC
#undef CONFIG_LIBC_NONE
#undef CONFIG_PKG_GLIBC
#undef CONFIG_PKG_UCLIBC

/*
 * Toolchain component options
 */
#define CONFIG_PKG_BASE_LIBS 1
#define CONFIG_PKG_LIBC_WANT_SHARED_LIBS 1
#define CONFIG_PKG_LIBC_WANT_CRT_FILES 1
#undef CONFIG_PKG_LIBC_WANT_HEADERS1
#undef CONFIG_PKG_LIBC_WANT_STATIC_LIBS
#undef CONFIG_PKG_LIBC_WANT_C_LOCALES
#define CONFIG_PKG_CXX_WANT_SHARED_LIBS 1
#undef CONFIG_PKG_CXX_WANT_HEADERS
#undef CONFIG_PKG_CXX_WANT_STATIC_LIBS
#define CONFIG_PKG_GCC_WANT_LIBGCC_SHARED 1
#define CONFIG_DYNAMIC_LINKER "/lib/ld.so.1"
#define CONFIG_SYS_WANT_MMU 1
#define CONFIG_SYS_WANT_SHARED 1

/*
 * Choose your toolchain
 */
#define CONFIG_TOOLCHAIN1 1
#undef CONFIG_TOOLCHAIN_CUSTOM
#define CONFIG_TOOLCHAIN "tc-fsl-x86lnx-e300c3-4.1.78-1.i386.rpm"
#define CONFIG_TOOLCHAIN_PATH "/opt/freescale/usr/local/gcc-4.1.78-eglibc-2.5.78-1/powerpc-e300c3-linux-gnu"
#define CONFIG_TOOLCHAIN_PREFIX "powerpc-e300c3-linux-gnu-"
#define CONFIG_TOOLCHAIN_CFLAGS "-mcpu=e300c3"

/*
 * Board hardware configuration
 */
#undef CONFIG_HWOPT_BASIC
#define CONFIG_HWOPT_CUSTOM 1

/*
 * Bootloader
 */
#undef CONFIG_BOOTLOADER1

/*
 * u-boot options
 */
#undef CONFIG_PKG_U_BOOT_CW
#define CONFIG_PKG_U_BOOT_BUILD_ARGS "OPTFLAGS=-Os"

/*
 * Choose your Kernel
 */
#undef CONFIG_KERNEL1
#define CONFIG_KERNEL_DIR_BUILD 1
#undef CONFIG_KERNEL_NONE
#define CONFIG_PKG_KERNEL "kernel26-dir-build"
#define CONFIG_PKG_KERNEL_PATH_PRECONFIG "/usr/src/linux-3.3.5"
#undef CONFIG_PKG_KERNEL_KBOUT
#undef CONFIG_PKG_KERNEL_FORCE
#undef CONFIG_PKG_KERNEL_WANT_CSCOPE
#define CONFIG_KERNEL_CONFIG1 1
#undef CONFIG_KERNEL_CONFIG2
#undef CONFIG_KERNEL_CONFIG3
#undef CONFIG_KERNEL_CONFIG4
#undef CONFIG_KERNEL_CONFIG5
#undef CONFIG_KERNEL_CONFIG_CUSTOM
#define CONFIG_PKG_KERNEL_PRECONFIG "mpc8315_xs1.defconfig"
#define CONFIG_PKG_KERNEL_WANT_HEADERS 1
#define CONFIG_PKG_KERNEL_WANT_CF 1
#define CONFIG_PKG_KERNEL_LEAVESRC 1
#define CONFIG_CUSTOM_DTC_NAME "mpc8315erdb"
#define CONFIG_SYSCFG_DTC_NAME "mpc8315erdb"
#define CONFIG_DISTRO "dist/lfs-5.1"

/*
 * Package selection
 */

/*
 * Package list
 */

/*
 * Common package selection list
 */
#undef CONFIG_PKG_APPTRK
#undef CONFIG_PKG_ASTERISK
#undef CONFIG_PKG_ATK
#undef CONFIG_PKG_AUTOCONF
#undef CONFIG_PKG_AUTOMAKE
#undef CONFIG_PKG_ALSA_LIB
#undef CONFIG_PKG_ALSA_UTILS
#undef CONFIG_PKG_BASH
#undef CONFIG_PKG_BIND
#undef CONFIG_PKG_BINUTILS
#undef CONFIG_PKG_BISON
#undef CONFIG_PKG_BLUEZ_HCIDUMP
#undef CONFIG_PKG_BLUEZ_LIBS
#undef CONFIG_PKG_BLUEZ_UTILS
#undef CONFIG_PKG_BOA
#undef CONFIG_PKG_BONNIE_PLUS_PLUS
#undef CONFIG_PKG_BRIDGE_UTILS
#define CONFIG_PKG_BUSYBOX 1
#define CONFIG_PKG_BUSYBOX_PRECONFIG "busybox.config"
#undef CONFIG_PKG_BUSYBOX_WANT_CF
#define CONFIG_PKG_BZIP2 1
#undef CONFIG_PKG_CAIRO
#define CONFIG_PKG_CAN4LINUX 1
#define CONFIG_PKG_CANTEST 1
#undef CONFIG_PKG_CCACHE
#undef CONFIG_PKG_CGICC
#undef CONFIG_PKG_CHEESE
#undef CONFIG_PKG_CLAMAV
#undef CONFIG_PKG_CONNTRACK_TOOLS
#undef CONFIG_PKG_COREUTILS
#define CONFIG_PKG_CPIO 1
#undef CONFIG_PKG_CPUFREQUTILS
#undef CONFIG_PKG_CRACKLIB
#undef CONFIG_PKG_CRAMFS
#define CONFIG_PKG_CURL 1
#undef CONFIG_PKG_DAEMONIZER
#undef CONFIG_PKG_DBUS
#undef CONFIG_PKG_DEVMEM2
#undef CONFIG_PKG_DHCP
#undef CONFIG_PKG_DB1
#undef CONFIG_PKG_DB4
#undef CONFIG_PKG_DBG
#undef CONFIG_PKG_DBUS_GLIB
#undef CONFIG_PKG_DEV
#undef CONFIG_PKG_MDEV
#define CONFIG_PKG_UDEV 1
#undef CONFIG_PKG_UDEV_WANT_AUTOMOUNT
#define CONFIG_PKG_UDEV_WANT_NON_RAID 1
#undef CONFIG_PKG_UDEV_WANT_IMX
#undef CONFIG_PKG_DEVFSD
#undef CONFIG_PKG_DEV_NONE
#undef CONFIG_PKG_DIFFUTILS
#undef CONFIG_PKG_DILLO2
#undef CONFIG_PKG_DIRECTFB
#undef CONFIG_PKG_DISTCC
#undef CONFIG_PKG_DOSFSTOOLS
#undef CONFIG_PKG_DROPBEAR

/*
 * dtc
 */
#define CONFIG_DTC 1

/*
 * dtc options
 */
#define CONFIG_DTC_PKG_BUILD 1
#undef CONFIG_DTC_DIR_BUILD
#define CONFIG_PKG_DTC "dtc"
#define CONFIG_PKG_DTC_WANT_FDT 1
#undef CONFIG_PKG_E2FSPROGS

/*
 * Enlightenment window manager packages
 */
#define CONFIG_CHOICE_ENLIGHTENMENT_NONE 1
#undef CONFIG_CHOICE_ENLIGHTENMENT
#undef CONFIG_PKG_ED
#undef CONFIG_PKG_EEL
#undef CONFIG_PKG_ENCHANT
#undef CONFIG_PKG_EOG
#define CONFIG_PKG_ETHTOOL 1
#undef CONFIG_PKG_EVOLUTION
#undef CONFIG_PKG_EVOLUTION_DATA_SERVER
#undef CONFIG_PKG_EVTEST
#undef CONFIG_PKG_EXPAT
#undef CONFIG_PKG_FAAD2
#undef CONFIG_PKG_FAKEROOT
#define CONFIG_PKG_FAKE_PROVIDES 1
#undef CONFIG_PKG_FARSIGHT
#undef CONFIG_PKG_FBPAN
#undef CONFIG_PKG_FBSET
#undef CONFIG_PKG_FBV
#undef CONFIG_PKG_FFMPEG
#undef CONFIG_PKG_FINDUTILS
#define CONFIG_PKG_FLEX 1
#undef CONFIG_PKG_FLTK2
#undef CONFIG_PKG_FONTCONFIG
#undef CONFIG_PKG_FREETYPE
#undef CONFIG_PKG_GAWK
#undef CONFIG_PKG_GCONF_DBUS
#undef CONFIG_PKG_GDBM
#undef CONFIG_PKG_GDB
#undef CONFIG_PKG_GENEXT2FS
#undef CONFIG_PKG_GENROMFS
#undef CONFIG_PKG_GEN_INIT_CPIO
#undef CONFIG_PKG_GETTEXT
#undef CONFIG_PKG_GIFLIB
#undef CONFIG_PKG_GIT
#undef CONFIG_PKG_GLIB2
#define CONFIG_PKG_GMP 1
#undef CONFIG_PKG_GNOME_DESKTOP
#undef CONFIG_PKG_GNOME_MIME_DATA
#undef CONFIG_PKG_GNOME_ICON_THEME
#undef CONFIG_PKG_GNOME_VFS
#undef CONFIG_PKG_GNOME_KEYRING
#undef CONFIG_PKG_GPSD
#undef CONFIG_PKG_GREP
#undef CONFIG_PKG_GROFF
#undef CONFIG_PKG_GSTREAMER_CORE
#undef CONFIG_PKG_GST_PLUGINS_FARSIGHT
#undef CONFIG_PKG_GTK2
#undef CONFIG_PKG_GTKHTML
#undef CONFIG_PKG_HAL
#undef CONFIG_PKG_GZIP
#define CONFIG_PKG_HDPARM 1
#undef CONFIG_PKG_HELLOWORLD
#undef CONFIG_PKG_HELLOWORLD_MOD
#undef CONFIG_PKG_HELP2MAN
#undef CONFIG_PKG_HESIOD
#define CONFIG_PKG_HOTPLUG 1
#undef CONFIG_PKG_HTTPD
#define CONFIG_PKG_I2C_TOOLS 1
#undef CONFIG_PKG_IOZONE
#define CONFIG_PKG_INPUT_UTILS 1
#undef CONFIG_PKG_IPROUTE
#undef CONFIG_PKG_INETUTILS
#define CONFIG_PKG_IPERF 1
#define CONFIG_PKG_OPENSWAN 1
#undef CONFIG_PKG_STRONGSWAN
#undef CONFIG_PKG_IPSEC_SUITE_NONE
#define CONFIG_PKG_IPSEC_TOOLS 1
#define CONFIG_PKG_IPSECADM 1
#define CONFIG_PKG_IPTABLES 1
#undef CONFIG_PKG_IPUTILS
#undef CONFIG_PKG_IRATTACH
#undef CONFIG_PKG_IRDADUMP
#undef CONFIG_PKG_ISO_CODES
#undef CONFIG_PKG_JSON_C
#undef CONFIG_PKG_KBD
#undef CONFIG_PKG_KEYFUZZ
#undef CONFIG_PKG_KRB5
#undef CONFIG_PKG_LESS
#undef CONFIG_PKG_LFS_UTILS
#undef CONFIG_PKG_LIBDAEMON
#undef CONFIG_PKG_LIBERATION_FONTS
#undef CONFIG_PKG_LIBART_LGPL
#undef CONFIG_PKG_LIBBONOBO
#undef CONFIG_PKG_LIBBONOBOUI
#undef CONFIG_PKG_LIBGCRYPT
#undef CONFIG_PKG_LIBGPG_ERROR
#undef CONFIG_PKG_LIBGLADE
#undef CONFIG_PKG_LIBGNOME
#undef CONFIG_PKG_LIBGNOMECANVAS
#undef CONFIG_PKG_LIBGNOMEUI
#undef CONFIG_PKG_LIBICONV
#undef CONFIG_PKG_LIBIDL
#undef CONFIG_PKG_LIBID3TAG
#undef CONFIG_PKG_LIBMAD
#undef CONFIG_PKG_LIBMPEG2
#undef CONFIG_PKG_LIBNETFILTER_CONNTRACK
#undef CONFIG_PKG_LIBNFNETLINK
#undef CONFIG_PKG_LIBJPEG
#define CONFIG_PKG_LIBELF 1
#undef CONFIG_PKG_LIBNET
#define CONFIG_PKG_LIBPCAP 1
#undef CONFIG_PKG_LIBPNG
#undef CONFIG_PKG_LIBOGG
#undef CONFIG_PKG_LIBOIL
#undef CONFIG_PKG_LIBRSVG
#undef CONFIG_PKG_LIBSOUP
#undef CONFIG_PKG_LIBTASN1
#define CONFIG_PKG_LIBTERMCAP 1
#undef CONFIG_PKG_LIBTHEORA
#undef CONFIG_PKG_LIBTIFF
#undef CONFIG_PKG_LIBTOOL
#define CONFIG_PKG_LIBUSB 1
#undef CONFIG_PKG_LIBVORBIS
#undef CONFIG_PKG_LIBXML2
#undef CONFIG_PKG_LIBXML_PLUS_PLUS
#undef CONFIG_PKG_LINUX_ATM
#undef CONFIG_PKG_LINUX_WLAN
#undef CONFIG_PKG_MPFR
#undef CONFIG_PKG_LKC
#undef CONFIG_PKG_LOGROTATE
#define CONFIG_PKG_LTP 1
#define CONFIG_PKG_LMBENCH 1
#define CONFIG_PKG_LM_SENSORS 1
#undef CONFIG_PKG_LRZSZ
#define CONFIG_PKG_LZO 1
#undef CONFIG_PKG_M4
#undef CONFIG_PKG_MADPLAY
#undef CONFIG_PKG_MAKE
#undef CONFIG_PKG_MAN

/*
 * Matchbox window manager packages
 */
#define CONFIG_CHOICE_MATCHBOX_NONE 1
#undef CONFIG_CHOICE_MATCHBOX
#undef CONFIG_PKG_MDADM
#define CONFIG_PKG_MERGE 1
#undef CONFIG_PKG_MICROWINDOWS
#undef CONFIG_PKG_MINICOM
#define CONFIG_PKG_MODEPS 1
#undef CONFIG_PKG_MODUTILS
#undef CONFIG_PKG_MODULE_INIT_TOOLS
#define CONFIG_MODUTILS_NONE 1
#undef CONFIG_PKG_MPLAYER
#undef CONFIG_PKG_MP3PLAY
#define CONFIG_PKG_MTD_UTILS 1
#undef CONFIG_PKG_MUX_SERVER
#undef CONFIG_PKG_MYSQL
#undef CONFIG_PKG_NAUTILUS
#define CONFIG_PKG_NCURSES 1
#define CONFIG_PKG_NCURSES_WANT_REDUCED_SET 1
#undef CONFIG_PKG_NET_SNMP
#define CONFIG_PKG_NET_TOOLS 1
#undef CONFIG_PKG_NETCAT
#undef CONFIG_PKG_NETPERF
#undef CONFIG_PKG_NFS_UTILS
#undef CONFIG_PKG_NSS_MDNS
#undef CONFIG_PKG_NTPCLIENT
#undef CONFIG_PKG_OPENOBEX
#undef CONFIG_PKG_OPENSSH
#define CONFIG_PKG_OPENSSL 1
#define CONFIG_PKG_OPENSSL_WANT_SEC 1
#undef CONFIG_PKG_OPROFILE
#undef CONFIG_PKG_ORBIT2
#undef CONFIG_PKG_PANGO
#undef CONFIG_PKG_PATCH
#define CONFIG_PKG_PCIUTILS 1
#undef CONFIG_PKG_PCMCIAUTILS
#undef CONFIG_PKG_PCRE
#define CONFIG_PKG_PERL 1
#undef CONFIG_PKG_PHP
#undef CONFIG_PKG_PIDENTD
#undef CONFIG_PKG_PKGCONFIG
#undef CONFIG_PKG_PLAY
#undef CONFIG_PKG_POPT
#undef CONFIG_PKG_PORTMAP
#define CONFIG_PKG_PPP 1
#define CONFIG_PKG_PPP_WANT_FILTER 1
#define CONFIG_PKG_PROCINFO 1
#undef CONFIG_PKG_PROCPS
#define CONFIG_PKG_PSMISC 1
#define CONFIG_PKG_PYTHON 1

/*
 * Qtopia
 */
#define CONFIG_QTOPIA_NONE 1
#undef CONFIG_PKG_QTOPIA
#undef CONFIG_PKG_QTOPIA_4

/*
 * Applications
 */

/*
 * Settings applications
 */
#define CONFIG_PKG_READLINE 1
#undef CONFIG_PKG_RPM
#undef CONFIG_PKG_RNG_TOOLS
#undef CONFIG_PKG_RSYNC
#undef CONFIG_PKG_RT_TESTS
#define CONFIG_PKG_RTCTEST 1
#undef CONFIG_PKG_SAMBA
#undef CONFIG_PKG_SASH
#undef CONFIG_PKG_SCHEDUTILS
#define CONFIG_PKG_SCREEN 1
#undef CONFIG_PKG_SDL
#undef CONFIG_PKG_SED
#undef CONFIG_PKG_SEQ
#define CONFIG_PKG_SETSERIAL 1
#undef CONFIG_PKG_SIMICSFS_MOD
#define CONFIG_PKG_SKELL 1
#undef CONFIG_PKG_SKELL_WANT_TERMINFO
#undef CONFIG_PKG_SPARSE
#undef CONFIG_PKG_STATSERIAL
#undef CONFIG_PKG_SQLITE
#undef CONFIG_PKG_STRACE
#define CONFIG_PKG_SYSCONFIG 1
#undef CONFIG_PKG_SYSFSUTILS
#undef CONFIG_PKG_SYSKLOGD
#define CONFIG_PKG_SYSSTAT 1
#undef CONFIG_PKG_SYSVINIT
#undef CONFIG_PKG_TAR
#undef CONFIG_PKG_TCLAP
#define CONFIG_PKG_TCPDUMP 1
#undef CONFIG_PKG_TCP_WRAPPERS
#define CONFIG_PKG_TERMCAP 1
#undef CONFIG_PKG_TEXINFO
#undef CONFIG_PKG_TIME
#undef CONFIG_PKG_TIMEZONE
#undef CONFIG_PKG_TINYLOGIN
#undef CONFIG_PKG_TINYPROXY
#undef CONFIG_PKG_TOTEM
#undef CONFIG_PKG_TOTEM_PL_PARSER
#undef CONFIG_PKG_TSLIB
#undef CONFIG_PKG_TUNCTL
#define CONFIG_PKG_USBUTILS 1
#undef CONFIG_PKG_UCLINUX_CKSUM
#undef CONFIG_PKG_UTIL_LINUX
#define CONFIG_PKG_U_BOOT_TOOLS 1
#undef CONFIG_PKG_UNIFDEF
#undef CONFIG_PKG_UNZIP
#undef CONFIG_PKG_VALGRIND
#undef CONFIG_PKG_VIM
#undef CONFIG_PKG_VPLAY
#define CONFIG_PKG_VSFTPD 1
#undef CONFIG_PKG_WATCHDOG
#undef CONFIG_PKG_WGET
#undef CONFIG_PKG_WHICH
#define CONFIG_PKG_WIRELESS_TOOLS 1
#undef CONFIG_PKG_WPA_SUPPLICANT
#undef CONFIG_PKG_XFSPROGS

/*
 * X11
 */
#define CONFIG_X11_NONE 1
#undef CONFIG_PKG_XORG_SERVER

/*
 * X11 libraries and packages
 */
#undef CONFIG_PKG_RANDRPROTO
#undef CONFIG_PKG_RENDERPROTO
#undef CONFIG_PKG_FIXESPROTO
#undef CONFIG_PKG_DAMAGEPROTO
#undef CONFIG_PKG_XF86DRIPROTO
#undef CONFIG_PKG_XCMISCPROTO
#undef CONFIG_PKG_XEXTPROTO
#undef CONFIG_PKG_XPROTO
#undef CONFIG_PKG_SCRNSAVERPROTO
#undef CONFIG_PKG_BIGREQSPROTO
#undef CONFIG_PKG_RESOURCEPROTO
#undef CONFIG_PKG_FONTSPROTO
#undef CONFIG_PKG_INPUTPROTO
#undef CONFIG_PKG_KBPROTO
#undef CONFIG_PKG_VIDEOPROTO
#undef CONFIG_PKG_COMPOSITEPROTO
#undef CONFIG_PKG_RECORDPROTO
#undef CONFIG_PKG_FONTCACHEPROTO
#undef CONFIG_PKG_XF86BIGFONTPROTO
#undef CONFIG_PKG_XCB_PROTO
#undef CONFIG_PKG_LIBPTHREAD_STUBS
#undef CONFIG_PKG_LIBFONTENC
#undef CONFIG_PKG_XTRANS
#undef CONFIG_PKG_LIBDRM
#undef CONFIG_PKG_PIXMAN
#undef CONFIG_PKG_LIBXCB
#undef CONFIG_PKG_LIBXKBFILE
#undef CONFIG_PKG_LIBXFONT
#undef CONFIG_PKG_LIBXDMCP
#undef CONFIG_PKG_LIBXAU
#undef CONFIG_PKG_LIBX11
#undef CONFIG_PKG_LIBXEXT
#undef CONFIG_PKG_LIBXFT
#undef CONFIG_PKG_LIBXRANDR
#undef CONFIG_PKG_LIBXRENDER
#undef CONFIG_PKG_LIBPCIACCESS
#undef CONFIG_PKG_FONTUTIL
#undef CONFIG_PKG_LIBICE
#undef CONFIG_PKG_LIBSM
#undef CONFIG_PKG_LIBXI
#undef CONFIG_PKG_LIBXPM
#undef CONFIG_PKG_LIBXT
#undef CONFIG_PKG_LIBXTST
#undef CONFIG_PKG_LIBXMU
#undef CONFIG_PKG_LIBXAW
#undef CONFIG_PKG_LIBXFIXES
#undef CONFIG_PKG_LIBXCURSOR
#undef CONFIG_PKG_LIBXXF86DGA
#undef CONFIG_PKG_XORG_X11_XKB_UTILS
#undef CONFIG_PKG_XORG_X11_PROTO_DEVEL
#undef CONFIG_PKG_YAFFS_UTILS
#undef CONFIG_PKG_ZAPTEL
#define CONFIG_PKG_ZLIB 1

/*
 * Additional Package selection
 */

/*
 * Target System Configuration
 */

/*
 * Options
 */
#define CONFIG_SYSCFG_HOSTNAME "iVolve XS1"
#define CONFIG_SYSCFG_WANT_LOGIN_TTY 1
#define CONFIG_SYSCFG_LOGING_TTY "::respawn:/sbin/getty -L ttyS0 115200 vt100"
#define CONFIG_SYSCFG_MODLIST ""
#define CONFIG_SYSCFG_START_UDEV 1
#define CONFIG_SYSCFG_START_NETWORK 1

/*
 * Network setup
 */

/*
 * 
 */
#define CONFIG_SYSCFG_IFACE0 1
#define CONFIG_SYSCFG_NET_INTERFACE0 "eth0"
#define CONFIG_SYSCFG_DHCPC0 1

/*
 * 
 */
#define CONFIG_SYSCFG_IFACE1 1
#define CONFIG_SYSCFG_NET_INTERFACE1 "eth1"
#define CONFIG_SYSCFG_DHCPC1 1

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE2

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE3

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE4

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE5

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE6

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE7

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE8

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE9
#define CONFIG_SYSCFG_DHCPC_CMD "udhcpc -b -i "
#undef CONFIG_SYSCFG_SETTIME
#undef CONFIG_SYSCFG_START_SYSLOG
#define CONFIG_SYSCFG_START_INETD 1
#define CONFIG_SYSCFG_INETD_ARGS ""

/*
 * Target Image Generation
 */

/*
 * Options
 */

/*
 * Choose your root filesystem image type
 */
#define CONFIG_DEPLOYMENT_JFFS2 1
#undef CONFIG_DEPLOYMENT_RAMDISK
#undef CONFIG_DEPLOYMENT_CRAMFS
#undef CONFIG_DEPLOYMENT_INITRAMFS
#undef CONFIG_DEPLOYMENT_ROMFS
#undef CONFIG_DEPLOYMENT_NFS
#define CONFIG_SYSCFG_DEPLOYMENT_STYLE "JFFS2"
#undef CONFIG_WANT_POST_BUILD_SCRIPT
#define CONFIG_DEPLOYMENT_ERASE_BLOCK_SIZE "128"
#undef CONFIG_SYSCFG_READONLY_FS
#define CONFIG_SYSCFG_TMPFS_SIZE "512k"
#define CONFIG_SYSCFG_RAM_DIRS "/tmp /var"
#define CONFIG_DEPLOYMENT_ROOTFS_DIR ""
#undef CONFIG_DEPLOYMENT_ROOTFS_KEEPSTAGE
#undef CONFIG_DEPLOYMENT_HL2SL
#define CONFIG_DEPLOYMENT_RM_DOCS 1
#define CONFIG_DEPLOYMENT_RM_BOOT 1
#define CONFIG_DEPLOYMENT_RM_USR_SRC 1
#define CONFIG_DEPLOYMENT_RM_USR_INCLUDE 1
#define CONFIG_DEPLOYMENT_RM_LOCALES 1
#define CONFIG_DEPLOYMENT_RM_USER_DIRS ""
#define CONFIG_DEPLOYMENT_RM_USER_FILES ""
#define CONFIG_DEPLOYMENT_RM_STATIC_LIBS 1
#define CONFIG_DEPLOYMENT_RM_RPMDB "/var/lib/rpm"
#define CONFIG_DEPLOYMENT_STRIP 1
#undef CONFIG_DEPLOYMENT_STRIP_MORE
#undef CONFIG_DEPLOYMENT_PADDING_EN
#define CONFIG_DEPLOYMENT_PAGESIZE_KB "2"
#define CONFIG_ERASE_BLOCK_SIZE "64"
#define CONFIG_CAP_UCLIBC 1
#define CONFIG_CAP_GLIBC 1
#define CONFIG_CAP_LFS_5_1 1
#define CONFIG_CAP_HAS_MMU 1
#define CONFIG_CAP_HAS_SHARED 1
#define CONFIG_E300C3_ARCH 1
#define CONFIG_PKG_GCC_NAME "nobuild"
#define CONFIG_SYSCFG_TMPFS "tmpfs"
#define CONFIG_INITTAB_LINE "::respawn:-/sbin/getty -L console 0 screen"
#define CONFIG_UCLIBC_DYNAMIC_LINKER "/lib/ld-uClibc.so.0"
#define CONFIG_GLIBC_DYNAMIC_LINKER "/lib/ld.so.1"
#define CONFIG_SYSCFG_BAUD "115200"
#define CONFIG_SYSCFG_CONSOLEDEV "ttyS0"
#define CONFIG_SYSCFG_BOOTLOADER "u-boot"
#define CONFIG_U_BOOT_IMAGE_TYPE "ppc"
#define CONFIG_SYSCFG_RUNKERNELADDR "0x0"
#define CONFIG_SYSCFG_LOADKERNELADDR "0x800000"
#define CONFIG_SYSCFG_LOADDTBADDR "0x9F0000"
#define CONFIG_SYSCFG_LOADRAMADDR "0xB00000"
#define CONFIG_SYSCFG_CUTARG "zImage"
#undef CONFIG_CAP_FSL_INT
#define CONFIG_LTIB_RELEASE "9.1.1"
